Handle Multiple Catch Blocks in Logging Analyzer
RockLib/RockLib.Analyzers pull request #12
Opened 2021-08-19 12:35 UTC by justin-avery

## Description

Each time a `LogEntry` is instantiated, all catch blocks are analyzed. This means that if there are two catch blocks, each containing a `new LogEntry()`, the `LogEntryCreatedWalker` will execute four times. Since the `LogWalkerCreatedWalker` uses the same instance during `LogEntry` instantiation, we need to make sure that we exit if we've already evaluated that the catch block to be valid.

2021-08-19 16:19 UTC, JustinMoss approved these changes
👍

2021-08-25 18:42 UTC, bfriesen requested changes
I see changes for checking if a log entry's Exception property is set with the catch exception. But I don't see any changes for checking if the exception parameter of a logging extension method comes from the catch exception. Does this work already? If so, we should have tests documenting this fact. Otherwise, it needs to be addressed.

Also found a few minor issues with tests.

2021-08-25 18:42 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers.Test/CaughtExceptionShouldBeLoggedAnalyzerTests.cs
> +        public async Task NoDiagnosticsReported9()
Method name should be "DiagnosticsReported7" and should be moved to the other positive tests, line 218.

2021-08-25 18:42 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers.Test/CaughtExceptionShouldBeLoggedAnalyzerTests.cs
> +             [|logger.Log(log)|];
Remove extra space.
```suggestion
            [|logger.Log(log)|];
```

2021-08-25 19:02 UTC, javery2 commented on Logging/RockLib.Logging.Analyzers.Test/CaughtExceptionShouldBeLoggedAnalyzerTests.cs
> +             [|logger.Log(log)|];
🤦‍♂️

2021-08-27 19:48 UTC, bfriesen approved these changes

2021-08-27 19:49 UTC, merged