Analyzer: Logs Should Have Message
RockLib/RockLib.Analyzers pull request #13
Opened 2021-08-24 13:29 UTC by justin-avery

## Description

Since a log without a message doesn't provide much value to anybody, this will warn if the message property is not provided or an empty string.

This covers: 
* Empty strings in logging methods
* Empty/missing value in `LogEntry` initializers
* Empty/missing value in `LogEntry` constructor
* Empty/missing value in `LogEntry.Message` property setter.

2021-08-25 15:36 UTC, JustinMoss approved these changes
👍

2021-08-25 15:36 UTC, JustinMoss commented on Logging/RockLib.Logging.Analyzers/AnalyzerReleases.Shipped.md
> +RockLib0008 | Usage | Warning | NoLogMessageSpecifiedAnalyzer, [Documentation](https://github.com/RockLib/RockLib.Analyzers/blob/main/Rules/RockLib0008.md)
I believe we don't add to shipped until it's actually released.

2021-08-25 19:11 UTC, bfriesen requested changes
There are some issues with test name and organization. The pattern we use for tests is to have a positive section, where the tests are all named `DiagnosticsReportedN` and verify that diagnostics were reported correctly. There's also a negative section, where the tests are all named `NoDiagnosticsReportedN` and verify scenarios where no diagnostics should be reported.

Also, I see no tests verifying that logging extension methods are reported on correctly, even though the code looks like it supports this feature. No mention of this in the rule file either.

2021-08-25 19:11 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers.sln
> +		..\Rules\RockLib0004.md = ..\Rules\RockLib0004.md
These rules are omitted on purpose - they're rules for analyzers not defined in this solution.

2021-08-25 19:11 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers/AnalyzerReleases.Shipped.md
> +RockLib0008 | Usage | Warning | NoLogMessageSpecifiedAnalyzer, [Documentation](https://github.com/RockLib/RockLib.Analyzers/blob/main/Rules/RockLib0008.md)
Agreed. New rules definitely don't belong here until the package is published.

2021-08-25 19:11 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers/NoLogMessageSpecifiedAnalyzer.cs
> +                    }
I think this will cause a lot of false positives, which is really bad for an analyzer to do. The message could be a parameter reference, a field reference, a method call (e.g. `StringBuilder.Build()`), and probably others. Maybe a better way is to flip it - search for null or empty string being passed as the message. That way, if the search fails to find a null or empty string, a false negative results instead of a false positive.

2021-08-25 19:11 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers/NoLogMessageSpecifiedAnalyzer.cs
> +                    var messageArg = arguments.FirstOrDefault(argument => argument.Parameter.Name == "message");
This is casting too wide of a net here. We should only look for a `message` argument when the method being called is a logging extension method.

2021-08-25 19:11 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers/NoLogMessageSpecifiedAnalyzer.cs
> +        private static readonly LocalizableString _messageFormat = "A message for the LogEntry cannot be null or empty";
This message is too specific - it describes one of the two cases that this analyzer supports. For example, this message would be inappropriate if it was a logging extension method that was called with a null message.

2021-08-26 12:47 UTC, javery2 commented on Logging/RockLib.Logging.Analyzers/NoLogMessageSpecifiedAnalyzer.cs
> +        private static readonly LocalizableString _messageFormat = "A message for the LogEntry cannot be null or empty";
"Present me" is frustrated with "past me".

2021-08-27 19:37 UTC, bfriesen requested changes
I don't see any tests for a `null` value for the message parameter/property. Should probably copy & paste within each existing test that passes empty string as the message parameter/property value. For example:

```c#
LogEntry logEntry1 = new LogEntry(){Message = """", Level = LogLevel.Debug};
logger.Log([|logEntry1|]);

LogEntry logEntry2 = new LogEntry(){Message = null, Level = LogLevel.Debug};
logger.Log([|logEntry2|]);
```

2021-08-27 19:37 UTC, bfriesen commented on Logging/RockLib.Logging.Analyzers/CommonExtensions.cs
> +
The question of "is this a logging extension method?" is solved in other analyzers by [capturing](https://github.com/RockLib/RockLib.Analyzers/blob/main/Logging/RockLib.Logging.Analyzers/CaughtExceptionShouldBeLoggedAnalyzer.cs#L38-L44) the `RockLib.Logging.LoggingExtensions` and `RockLib.Logging.SafeLogging.SafeLoggingExtensions` types and [determining](https://github.com/RockLib/RockLib.Analyzers/blob/main/Logging/RockLib.Logging.Analyzers/CaughtExceptionShouldBeLoggedAnalyzer.cs#L87-L88) if the method symbol's containing type is either. Doing it this way eliminates the possibility of false positives.

2021-08-27 20:53 UTC, bfriesen approved these changes
![Very nice!](https://ichef.bbci.co.uk/news/976/cpsprodpb/9180/production/_115084273_cfbc1938-3feb-4a79-88f4-593f24d3ad3b.jpg "Very nice!")

2021-08-27 20:53 UTC, merged